# Chapter 6: Foundational models and Semantic IDs

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/kimfalk/modern-recommender-systems/blob/main/notebooks/chapter-06/example_notebook.ipynb)

This notebook introduces the basics of recommender systems.

In [1]:
# Install datasets library for HuggingFace
!pip install -q datasets
!pip install -q mlflow

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [2]:
from pathlib import Path
import sys

project_root = Path.cwd()
while project_root != project_root.parent and not (project_root / "recsys").exists():
    project_root = project_root.parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

print(f"Added to sys.path: {project_root}")

Added to sys.path: /Users/kfalk/private/repos/manning/modern-recommender-systems

In [3]:
from recsys.utils.colab import setup_colab_environment, get_data_path, check_gpu
# One-line setup for Colab users
setup_colab_environment()

# Check GPU availability
check_gpu()

Not running in Colab, skipping setup.
⚠ No GPU detected.

False

In [4]:
# Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from recsys.data import loaders
from recsys.semantic_ids.utils import prepare_data
from recsys.semantic_ids.training import run_pipeline_debug
from recsys.semantic_ids.evaluations import evaluate_semantic_ids

DATA_PATH = get_data_path()

In [5]:
print("Ready to build recommender systems!")

Ready to build recommender systems!

In [6]:
from recsys.data.loaders import load_movielens_descriptions

movies = load_movielens_descriptions(data_dir=DATA_PATH)

movies.head()

Downloading movie descriptions from HuggingFace...
Downloaded and saved movie descriptions to /Users/kfalk/private/repos/manning/modern-recommender-systems/notebooks/data/movie_descriptions.csv
Loaded 9837 movie descriptions
Failed to download descriptions: 'title'
Returning empty DataFrame...

Empty DataFrame
Columns: []
Index: []

In [7]:
# Reload the loaders module to pick up latest changes
import importlib
import recsys.data.loaders
importlib.reload(recsys.data.loaders)

In [8]:
# Load movie descriptions from HuggingFace
from recsys.data.loaders import load_movielens_descriptions

movies_descriptions = load_movielens_descriptions(data_dir=DATA_PATH)

Loaded 9837 movie descriptions from cache

In [9]:
# Check the structure and columns

movies_descriptions.rename(columns={'Overview': 'description',
                                    'Title': 'title',
                                    'Genre': 'genres'}, inplace=True)
print(f"Shape: {movies_descriptions.shape}")
print(f"\nColumns: {movies_descriptions.columns.tolist()}")
movies_descriptions.head()

Shape: (9837, 9)

Columns: ['Release_Date', 'title', 'description', 'Popularity', 'Vote_Count', 'Vote_Average', 'Original_Language', 'genres', 'Poster_Url']

,Release_Date,title,description,Popularity,Vote_Count,Vote_Average,Original_Language,genres,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [10]:
movies_descriptions = movies_descriptions[~movies_descriptions['title'].isna()]
movies_descriptions.shape

(9828, 9)

In [11]:
codebook_sizes = [16, 32, 128]  # Tiny capacity: max 512 combinations for 9,837 movies
internal_dim = 512  # Match input dimension
usage_loss_weight = 2.0  # Very strong penalty for imbalanced usage
epochs = 500  # Fewer epochs for faster iteration

In [12]:
import mlflow
import mlflow.pytorch

# Set experiment name
mlflow.set_experiment("semantic-ids-experiments")

<Experiment: artifact_location='/Users/kfalk/work/manning/modern-recommender-systems/notebooks/chapter-06/mlruns/1', creation_time=1771765791832, experiment_id='1', last_update_time=1771765791832, lifecycle_stage='active', name='semantic-ids-experiments', tags={}, workspace='default'>

In [13]:
recreate_embeddings = True

In [14]:
# Reload the module to pick up the fixes
import importlib
import recsys.semantic_ids.semantic_ids_pipeline
importlib.reload(recsys.semantic_ids.semantic_ids_pipeline)
importlib.reload(recsys.semantic_ids.training)
importlib.reload(recsys.semantic_ids.rqvae)
importlib.reload(recsys.semantic_ids.vector_quantizer)
importlib.reload(recsys.semantic_ids.evaluations)

# Now test with the fixed code
from recsys.semantic_ids.semantic_ids_pipeline import SemanticIDPipeline

from recsys.semantic_ids.utils import prepare_data

with mlflow.start_run(run_name="aggressive-clustering"):
    
    # Log parameters
    mlflow.log_params({
        "codebook_sizes": codebook_sizes,
        "internal_dim": internal_dim,
        "usage_loss_weight": usage_loss_weight,
        "epochs": epochs,
        "variance_weight": 1.0  # if using variance regularization
    })
   
    pipeline = SemanticIDPipeline(codebook_sizes, 
                                internal_dim,
                                usage_loss_weight=usage_loss_weight)

    if recreate_embeddings:
        texts = prepare_data(movies_descriptions)
        print("\nEncoding texts...")
        embeddings = pipeline.text_encoder.encode(texts, show_progress_bar=True)
        recreate_embeddings = False
            
    data_tensor = pipeline.initialize_data_with_embeddings(embeddings)
    pipeline.train(data_tensor, epochs=epochs)

    df_enriched = pipeline.inference(movies_descriptions, data_tensor)
    evaluate_semantic_ids(pipeline, df_enriched, data_tensor, codebook_sizes)
    # Log evaluation metrics
    num_clusters = df_enriched['semantic_id'].nunique()
    avg_cluster_size = len(df_enriched) / num_clusters
    
    mlflow.log_metrics({
        "num_unique_clusters": num_clusters,
        "avg_cluster_size": avg_cluster_size,
        "total_items": len(df_enriched)
    })
    
    # Save and log the model
    import torch
    import os
    
    # Create artifacts directory if it doesn't exist
    os.makedirs("mlflow_artifacts", exist_ok=True)
    
    # Save model state dict
    model_path = "mlflow_artifacts/rqvae_model.pth"
    torch.save(pipeline.rqvae.state_dict(), model_path)
    
    # Log as artifact
    mlflow.log_artifact(model_path)

Loading BERT...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Encoding Text...

Encoding texts...

Batches:   0%|          | 0/308 [00:00<?, ?it/s]

Initializing codebooks...
Input embeddings: mean=-0.0005, std=0.0510
Encoder output: mean=-0.0000, std=1.0000, shape=torch.Size([9828, 512])
Avg pairwise distance (first 100): 20.8146

  Level 1:
    Residual: mean=-0.0000, std=1.0000, min=-4.7438, max=4.5273
    K-means: 55 iters

  Level 2:
    Residual: mean=0.0000, std=0.6357, min=-3.3757, max=3.5264
    K-means: 44 iters

  Level 3:
    Residual: mean=-0.0000, std=0.6095, min=-3.3015, max=3.2688
    K-means: 33 iters
Training RQ-VAE...

  0%|          | 0/500 [00:00<?, ?it/s]

DEBUG: batch shape: torch.Size([64, 384])
DEBUG: reconstructed shape: torch.Size([64, 384])
  [VQ Debug] e_loss=0.1050, q_loss=0.1050, usage=0.0145, total=0.1866

  1%|          | 4/500 [00:06<12:57,  1.57s/it, loss=1.8227, recon=0.0050, vq=1.5799, div=0]

  [VQ Debug] e_loss=0.0232, q_loss=0.0232, usage=0.3532, total=0.7413
  [VQ Debug] e_loss=0.0278, q_loss=0.0278, usage=0.3485, total=0.7388
  [VQ Debug] e_loss=0.0298, q_loss=0.0298, usage=0.3391, total=0.7228
  [VQ Debug] e_loss=0.0467, q_loss=0.0467, usage=0.1781, total=0.4264

  2%|▏         | 10/500 [00:15<12:52,  1.58s/it, loss=1.5407, recon=0.0033, vq=1.3131, div=0]

  [VQ Debug] e_loss=0.0309, q_loss=0.0309, usage=0.1534, total=0.3531

  2%|▏         | 11/500 [00:16<12:27,  1.53s/it, loss=1.4769, recon=0.0031, vq=1.2510, div=0]

  [VQ Debug] e_loss=0.0341, q_loss=0.0341, usage=0.1424, total=0.3360

  2%|▏         | 12/500 [00:18<12:23,  1.52s/it, loss=1.3916, recon=0.0030, vq=1.1668, div=0]

  [VQ Debug] e_loss=0.0140, q_loss=0.0140, usage=0.2943, total=0.6095
  [VQ Debug] e_loss=0.0225, q_loss=0.0225, usage=0.0885, total=0.2109

  3%|▎         | 13/500 [00:19<12:06,  1.49s/it, loss=1.3814, recon=0.0029, vq=1.1580, div=0]

  [VQ Debug] e_loss=0.0370, q_loss=0.0370, usage=0.1553, total=0.3660

  3%|▎         | 14/500 [00:21<12:01,  1.48s/it, loss=1.3560, recon=0.0028, vq=1.1338, div=0]

  [VQ Debug] e_loss=0.0221, q_loss=0.0221, usage=0.0830, total=0.1992

  3%|▎         | 16/500 [00:24<11:42,  1.45s/it, loss=1.2209, recon=0.0026, vq=1.0011, div=0]

  [VQ Debug] e_loss=0.0222, q_loss=0.0222, usage=0.0695, total=0.1723
  [VQ Debug] e_loss=0.0161, q_loss=0.0161, usage=0.2102, total=0.4446

  4%|▎         | 18/500 [00:27<11:31,  1.44s/it, loss=1.1439, recon=0.0025, vq=0.9263, div=0]

  [VQ Debug] e_loss=0.0145, q_loss=0.0145, usage=0.2005, total=0.4227
  [VQ Debug] e_loss=0.0180, q_loss=0.0180, usage=0.1974, total=0.4218

  4%|▍         | 21/500 [00:32<14:10,  1.78s/it, loss=0.9961, recon=0.0023, vq=0.7817, div=0]

  [VQ Debug] e_loss=0.0163, q_loss=0.0163, usage=0.1678, total=0.3600

  4%|▍         | 22/500 [00:33<13:20,  1.67s/it, loss=0.9662, recon=0.0023, vq=0.7524, div=0]

  [VQ Debug] e_loss=0.0154, q_loss=0.0154, usage=0.1621, total=0.3473

  5%|▍         | 24/500 [00:38<12:24,  1.56s/it, loss=0.8637, recon=0.0022, vq=0.6522, div=0]

Epoch 25:
  Loss: 0.863707
  Recon: 0.002155
  VQ: 0.652236
  Unique semantic IDs: 6072/9828 (61.8%)

  5%|▌         | 25/500 [00:38<12:45,  1.61s/it, loss=0.8637, recon=0.0022, vq=0.6522, div=0]

  Level 1: 16/16 (100.0%) | Perplexity: 12.3
  Level 2: 32/32 (100.0%) | Perplexity: 28.4
  Level 3: 123/128 (96.1%) | Perplexity: 59.3

  5%|▌         | 27/500 [00:41<12:06,  1.54s/it, loss=0.8098, recon=0.0021, vq=0.5997, div=0]

  [VQ Debug] e_loss=0.0145, q_loss=0.0145, usage=0.1361, total=0.2939
  [VQ Debug] e_loss=0.0387, q_loss=0.0387, usage=0.0845, total=0.2270
  [VQ Debug] e_loss=0.0227, q_loss=0.0227, usage=0.0328, total=0.0996

  6%|▋         | 32/500 [00:49<11:46,  1.51s/it, loss=0.7505, recon=0.0020, vq=0.5432, div=0]

  [VQ Debug] e_loss=0.0357, q_loss=0.0357, usage=0.0830, total=0.2195
  [VQ Debug] e_loss=0.0321, q_loss=0.0321, usage=0.0805, total=0.2093

  7%|▋         | 34/500 [00:52<11:45,  1.51s/it, loss=0.7022, recon=0.0020, vq=0.4957, div=0]

  [VQ Debug] e_loss=0.0358, q_loss=0.0358, usage=0.0803, total=0.2141

  8%|▊         | 39/500 [00:59<11:06,  1.45s/it, loss=0.6968, recon=0.0019, vq=0.4929, div=0]

  [VQ Debug] e_loss=0.0346, q_loss=0.0346, usage=0.0743, total=0.2005
  [VQ Debug] e_loss=0.0110, q_loss=0.0110, usage=0.0954, total=0.2073

 10%|▉         | 49/500 [01:16<11:53,  1.58s/it, loss=0.6929, recon=0.0019, vq=0.4926, div=0]

Epoch 50:
  Loss: 0.692852
  Recon: 0.001854
  VQ: 0.492592
  Unique semantic IDs: 6941/9828 (70.6%)
  Level 1: 15/16 (93.8%) | Perplexity: 12.5
  Level 2: 32/32 (100.0%) | Perplexity: 30.2
  Level 3: 121/128 (94.5%) | Perplexity: 79.0

 10%|█         | 50/500 [01:16<12:21,  1.65s/it, loss=0.6929, recon=0.0019, vq=0.4926, div=0]

  [VQ Debug] e_loss=0.0363, q_loss=0.0363, usage=0.0927, total=0.2398

 10%|█         | 52/500 [01:19<11:48,  1.58s/it, loss=0.6680, recon=0.0018, vq=0.4683, div=0]

  [VQ Debug] e_loss=0.0241, q_loss=0.0241, usage=0.0100, total=0.0561

 11%|█         | 53/500 [01:21<11:40,  1.57s/it, loss=0.6755, recon=0.0018, vq=0.4760, div=0]

  [VQ Debug] e_loss=0.0229, q_loss=0.0229, usage=0.0095, total=0.0532
  [VQ Debug] e_loss=0.0460, q_loss=0.0460, usage=0.0984, total=0.2657

 11%|█         | 55/500 [01:23<11:07,  1.50s/it, loss=0.6853, recon=0.0018, vq=0.4864, div=0]

  [VQ Debug] e_loss=0.0416, q_loss=0.0416, usage=0.1040, total=0.2704

 11%|█         | 56/500 [01:25<10:53,  1.47s/it, loss=0.6859, recon=0.0018, vq=0.4868, div=0]

  [VQ Debug] e_loss=0.0139, q_loss=0.0139, usage=0.0743, total=0.1696

 12%|█▏        | 59/500 [01:29<10:35,  1.44s/it, loss=0.6947, recon=0.0018, vq=0.4965, div=0]

  [VQ Debug] e_loss=0.0126, q_loss=0.0126, usage=0.0720, total=0.1628
  [VQ Debug] e_loss=0.0119, q_loss=0.0119, usage=0.0731, total=0.1642

 13%|█▎        | 64/500 [01:36<10:22,  1.43s/it, loss=0.6136, recon=0.0018, vq=0.4174, div=0]

  [VQ Debug] e_loss=0.0133, q_loss=0.0133, usage=0.0507, total=0.1214

 13%|█▎        | 65/500 [01:38<10:18,  1.42s/it, loss=0.5930, recon=0.0018, vq=0.3970, div=0]

  [VQ Debug] e_loss=0.0125, q_loss=0.0125, usage=0.0500, total=0.1189
  [VQ Debug] e_loss=0.0383, q_loss=0.0383, usage=0.0851, total=0.2275

 13%|█▎        | 67/500 [01:41<10:25,  1.44s/it, loss=0.5937, recon=0.0018, vq=0.3983, div=0]

  [VQ Debug] e_loss=0.0121, q_loss=0.0121, usage=0.0522, total=0.1225

 14%|█▍        | 71/500 [01:46<10:14,  1.43s/it, loss=0.5929, recon=0.0018, vq=0.3984, div=0]

  [VQ Debug] e_loss=0.0136, q_loss=0.0136, usage=0.0506, total=0.1215

 15%|█▍        | 74/500 [01:53<11:07,  1.57s/it, loss=0.6064, recon=0.0018, vq=0.4123, div=0]

Epoch 75:
  Loss: 0.606393
  Recon: 0.001761
  VQ: 0.412330
  Unique semantic IDs: 7342/9828 (74.7%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.7
  Level 2: 32/32 (100.0%) | Perplexity: 30.7
  Level 3: 128/128 (100.0%) | Perplexity: 88.7

 16%|█▌        | 78/500 [01:58<11:13,  1.60s/it, loss=0.5944, recon=0.0018, vq=0.4010, div=0]

  [VQ Debug] e_loss=0.0433, q_loss=0.0433, usage=0.0843, total=0.2336

 16%|█▌        | 80/500 [02:01<10:32,  1.50s/it, loss=0.5888, recon=0.0018, vq=0.3956, div=0]

  [VQ Debug] e_loss=0.0247, q_loss=0.0247, usage=0.0076, total=0.0523

 17%|█▋        | 83/500 [02:05<10:02,  1.44s/it, loss=0.5899, recon=0.0018, vq=0.3974, div=0]

  [VQ Debug] e_loss=0.0479, q_loss=0.0479, usage=0.0850, total=0.2420
  [VQ Debug] e_loss=0.0142, q_loss=0.0142, usage=0.0451, total=0.1115

 17%|█▋        | 86/500 [02:09<09:48,  1.42s/it, loss=0.5897, recon=0.0017, vq=0.3976, div=0]

  [VQ Debug] e_loss=0.0391, q_loss=0.0391, usage=0.0848, total=0.2282

 18%|█▊        | 91/500 [02:17<10:28,  1.54s/it, loss=0.5879, recon=0.0017, vq=0.3966, div=0]

  [VQ Debug] e_loss=0.0285, q_loss=0.0285, usage=0.0079, total=0.0587

 19%|█▉        | 94/500 [02:21<10:36,  1.57s/it, loss=0.5945, recon=0.0017, vq=0.4033, div=0]

  [VQ Debug] e_loss=0.0156, q_loss=0.0156, usage=0.0474, total=0.1183
  [VQ Debug] e_loss=0.0144, q_loss=0.0144, usage=0.0467, total=0.1151

 19%|█▉        | 95/500 [02:23<10:27,  1.55s/it, loss=0.6006, recon=0.0017, vq=0.4099, div=0]

  [VQ Debug] e_loss=0.0474, q_loss=0.0474, usage=0.0840, total=0.2390

 20%|█▉        | 99/500 [02:31<10:26,  1.56s/it, loss=0.5927, recon=0.0017, vq=0.4027, div=0]

Epoch 100:
  Loss: 0.592713
  Recon: 0.001717
  VQ: 0.402693
  Unique semantic IDs: 7490/9828 (76.2%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 30.4
  Level 3: 127/128 (99.2%) | Perplexity: 97.6

 21%|██        | 103/500 [02:35<09:47,  1.48s/it, loss=0.5984, recon=0.0017, vq=0.4087, div=0]

  [VQ Debug] e_loss=0.0166, q_loss=0.0166, usage=0.0434, total=0.1117

 21%|██        | 106/500 [02:41<11:54,  1.81s/it, loss=0.6097, recon=0.0017, vq=0.4201, div=0]

  [VQ Debug] e_loss=0.0464, q_loss=0.0464, usage=0.0838, total=0.2372
  [VQ Debug] e_loss=0.0459, q_loss=0.0459, usage=0.0843, total=0.2374

 22%|██▏       | 108/500 [02:44<10:55,  1.67s/it, loss=0.5999, recon=0.0017, vq=0.4107, div=0]

  [VQ Debug] e_loss=0.0184, q_loss=0.0184, usage=0.0456, total=0.1187
  [VQ Debug] e_loss=0.0315, q_loss=0.0315, usage=0.0046, total=0.0564
  [VQ Debug] e_loss=0.0147, q_loss=0.0147, usage=0.0455, total=0.1130

 22%|██▏       | 109/500 [02:46<11:17,  1.73s/it, loss=0.5961, recon=0.0017, vq=0.4070, div=0]

  [VQ Debug] e_loss=0.0270, q_loss=0.0270, usage=0.0064, total=0.0533

 23%|██▎       | 116/500 [02:57<09:58,  1.56s/it, loss=0.6074, recon=0.0017, vq=0.4190, div=0]

  [VQ Debug] e_loss=0.0332, q_loss=0.0332, usage=0.0070, total=0.0638

 24%|██▍       | 121/500 [03:04<09:29,  1.50s/it, loss=0.5978, recon=0.0017, vq=0.4103, div=0]

  [VQ Debug] e_loss=0.0297, q_loss=0.0297, usage=0.0081, total=0.0607

 24%|██▍       | 122/500 [03:06<09:30,  1.51s/it, loss=0.5995, recon=0.0017, vq=0.4120, div=0]

  [VQ Debug] e_loss=0.0335, q_loss=0.0335, usage=0.0064, total=0.0630
  [VQ Debug] e_loss=0.0271, q_loss=0.0271, usage=0.0063, total=0.0532
  [VQ Debug] e_loss=0.0532, q_loss=0.0532, usage=0.0843, total=0.2483

 25%|██▍       | 123/500 [03:07<09:49,  1.56s/it, loss=0.6069, recon=0.0017, vq=0.4194, div=0]

  [VQ Debug] e_loss=0.0319, q_loss=0.0319, usage=0.0076, total=0.0631

 25%|██▍       | 124/500 [03:10<09:44,  1.56s/it, loss=0.5972, recon=0.0017, vq=0.4098, div=0]

Epoch 125:
  Loss: 0.597171
  Recon: 0.001692
  VQ: 0.409766
  Unique semantic IDs: 7377/9828 (75.1%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 30.9
  Level 3: 127/128 (99.2%) | Perplexity: 96.0

 25%|██▌       | 125/500 [03:11<10:02,  1.61s/it, loss=0.5972, recon=0.0017, vq=0.4098, div=0]

  [VQ Debug] e_loss=0.0582, q_loss=0.0582, usage=0.0852, total=0.2577

 26%|██▌       | 131/500 [03:20<09:17,  1.51s/it, loss=0.6189, recon=0.0017, vq=0.4316, div=0]

  [VQ Debug] e_loss=0.0595, q_loss=0.0595, usage=0.0852, total=0.2596

 27%|██▋       | 134/500 [03:25<09:47,  1.60s/it, loss=0.6045, recon=0.0017, vq=0.4179, div=0]

  [VQ Debug] e_loss=0.0153, q_loss=0.0153, usage=0.0388, total=0.1006
  [VQ Debug] e_loss=0.0466, q_loss=0.0466, usage=0.0854, total=0.2408

 27%|██▋       | 137/500 [03:29<09:26,  1.56s/it, loss=0.6264, recon=0.0017, vq=0.4395, div=0]

  [VQ Debug] e_loss=0.0306, q_loss=0.0306, usage=0.0074, total=0.0606

 29%|██▉       | 145/500 [03:42<09:12,  1.56s/it, loss=0.5969, recon=0.0017, vq=0.4112, div=0]

  [VQ Debug] e_loss=0.0298, q_loss=0.0298, usage=0.0058, total=0.0562

 29%|██▉       | 147/500 [03:45<09:01,  1.54s/it, loss=0.6007, recon=0.0017, vq=0.4150, div=0]

  [VQ Debug] e_loss=0.0320, q_loss=0.0320, usage=0.0064, total=0.0608

 30%|██▉       | 148/500 [03:46<08:57,  1.53s/it, loss=0.6012, recon=0.0017, vq=0.4158, div=0]

  [VQ Debug] e_loss=0.0192, q_loss=0.0192, usage=0.0432, total=0.1152
  [VQ Debug] e_loss=0.0178, q_loss=0.0178, usage=0.0443, total=0.1152

 30%|██▉       | 149/500 [03:50<09:20,  1.60s/it, loss=0.6063, recon=0.0017, vq=0.4210, div=0]

Epoch 150:
  Loss: 0.606328
  Recon: 0.001675
  VQ: 0.421004
  Unique semantic IDs: 7211/9828 (73.4%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 30.4
  Level 3: 128/128 (100.0%) | Perplexity: 97.7

 30%|███       | 150/500 [03:50<09:58,  1.71s/it, loss=0.6063, recon=0.0017, vq=0.4210, div=0]

  [VQ Debug] e_loss=0.0467, q_loss=0.0467, usage=0.0853, total=0.2407

 30%|███       | 152/500 [03:53<09:25,  1.63s/it, loss=0.5849, recon=0.0017, vq=0.4000, div=0]

  [VQ Debug] e_loss=0.0367, q_loss=0.0367, usage=0.0080, total=0.0711

 31%|███       | 155/500 [03:57<08:34,  1.49s/it, loss=0.6083, recon=0.0017, vq=0.4232, div=0]

  [VQ Debug] e_loss=0.0176, q_loss=0.0176, usage=0.0415, total=0.1093
  [VQ Debug] e_loss=0.0301, q_loss=0.0301, usage=0.0073, total=0.0598

 32%|███▏      | 161/500 [04:06<08:18,  1.47s/it, loss=0.6129, recon=0.0017, vq=0.4279, div=0]

  [VQ Debug] e_loss=0.0293, q_loss=0.0293, usage=0.0064, total=0.0567

 32%|███▏      | 162/500 [04:08<08:13,  1.46s/it, loss=0.6041, recon=0.0017, vq=0.4192, div=0]

  [VQ Debug] e_loss=0.0530, q_loss=0.0530, usage=0.0846, total=0.2487

 33%|███▎      | 163/500 [04:09<08:12,  1.46s/it, loss=0.6061, recon=0.0017, vq=0.4216, div=0]

  [VQ Debug] e_loss=0.0171, q_loss=0.0171, usage=0.0358, total=0.0972

 33%|███▎      | 167/500 [04:15<07:55,  1.43s/it, loss=0.6065, recon=0.0017, vq=0.4221, div=0]

  [VQ Debug] e_loss=0.0559, q_loss=0.0559, usage=0.0854, total=0.2546

 34%|███▍      | 169/500 [04:18<07:51,  1.43s/it, loss=0.6077, recon=0.0017, vq=0.4236, div=0]

  [VQ Debug] e_loss=0.0353, q_loss=0.0353, usage=0.0106, total=0.0741

 34%|███▍      | 170/500 [04:19<07:50,  1.43s/it, loss=0.6101, recon=0.0017, vq=0.4258, div=0]

  [VQ Debug] e_loss=0.0192, q_loss=0.0192, usage=0.0401, total=0.1090

 34%|███▍      | 172/500 [04:22<07:54,  1.45s/it, loss=0.6132, recon=0.0017, vq=0.4292, div=0]

  [VQ Debug] e_loss=0.0340, q_loss=0.0340, usage=0.0062, total=0.0635

 35%|███▍      | 173/500 [04:24<07:51,  1.44s/it, loss=0.6189, recon=0.0017, vq=0.4346, div=0]

  [VQ Debug] e_loss=0.0354, q_loss=0.0354, usage=0.0069, total=0.0668

 35%|███▍      | 174/500 [04:26<07:47,  1.43s/it, loss=0.6192, recon=0.0017, vq=0.4352, div=0]

Epoch 175:
  Loss: 0.619199
  Recon: 0.001665
  VQ: 0.435238
  Unique semantic IDs: 7367/9828 (75.0%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.7
  Level 2: 32/32 (100.0%) | Perplexity: 31.1
  Level 3: 128/128 (100.0%) | Perplexity: 98.7

 35%|███▌      | 177/500 [04:30<08:12,  1.52s/it, loss=0.5963, recon=0.0017, vq=0.4122, div=0]

  [VQ Debug] e_loss=0.0305, q_loss=0.0305, usage=0.0096, total=0.0649

 36%|███▌      | 181/500 [04:36<08:34,  1.61s/it, loss=0.6136, recon=0.0017, vq=0.4299, div=0]

  [VQ Debug] e_loss=0.0513, q_loss=0.0513, usage=0.0850, total=0.2468
  [VQ Debug] e_loss=0.0203, q_loss=0.0203, usage=0.0372, total=0.1048

 37%|███▋      | 183/500 [04:39<08:30,  1.61s/it, loss=0.6037, recon=0.0017, vq=0.4203, div=0]

  [VQ Debug] e_loss=0.0557, q_loss=0.0557, usage=0.0845, total=0.2526

 37%|███▋      | 184/500 [04:41<08:24,  1.60s/it, loss=0.6056, recon=0.0017, vq=0.4222, div=0]

  [VQ Debug] e_loss=0.0174, q_loss=0.0174, usage=0.0302, total=0.0865

 37%|███▋      | 186/500 [04:44<08:00,  1.53s/it, loss=0.6039, recon=0.0017, vq=0.4204, div=0]

  [VQ Debug] e_loss=0.0559, q_loss=0.0559, usage=0.0852, total=0.2544

 38%|███▊      | 189/500 [04:48<07:40,  1.48s/it, loss=0.5967, recon=0.0017, vq=0.4137, div=0]

  [VQ Debug] e_loss=0.0561, q_loss=0.0561, usage=0.0848, total=0.2537

 38%|███▊      | 191/500 [04:52<08:10,  1.59s/it, loss=0.6081, recon=0.0017, vq=0.4248, div=0]

  [VQ Debug] e_loss=0.0372, q_loss=0.0372, usage=0.0076, total=0.0710

 38%|███▊      | 192/500 [04:53<08:28,  1.65s/it, loss=0.6121, recon=0.0017, vq=0.4289, div=0]

  [VQ Debug] e_loss=0.0208, q_loss=0.0208, usage=0.0348, total=0.1007

 39%|███▊      | 193/500 [04:55<08:28,  1.66s/it, loss=0.6115, recon=0.0017, vq=0.4282, div=0]

  [VQ Debug] e_loss=0.0175, q_loss=0.0175, usage=0.0346, total=0.0954

 39%|███▉      | 197/500 [05:02<08:35,  1.70s/it, loss=0.6082, recon=0.0017, vq=0.4255, div=0]

  [VQ Debug] e_loss=0.0546, q_loss=0.0546, usage=0.0862, total=0.2543
  [VQ Debug] e_loss=0.0370, q_loss=0.0370, usage=0.0092, total=0.0739

 40%|███▉      | 199/500 [05:06<09:03,  1.80s/it, loss=0.6050, recon=0.0017, vq=0.4225, div=0]

  [VQ Debug] e_loss=0.0612, q_loss=0.0612, usage=0.0844, total=0.2605
  [VQ Debug] e_loss=0.0167, q_loss=0.0167, usage=0.0304, total=0.0858

 40%|███▉      | 199/500 [05:07<09:03,  1.80s/it, loss=0.5976, recon=0.0017, vq=0.4149, div=0]

Epoch 200:
  Loss: 0.597586
  Recon: 0.001662
  VQ: 0.414860
  Unique semantic IDs: 7317/9828 (74.5%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 30.6
  Level 3: 128/128 (100.0%) | Perplexity: 101.0

 40%|████      | 201/500 [05:09<08:35,  1.72s/it, loss=0.5844, recon=0.0016, vq=0.4028, div=0]

  [VQ Debug] e_loss=0.0368, q_loss=0.0368, usage=0.0064, total=0.0679

 41%|████      | 204/500 [05:13<07:46,  1.58s/it, loss=0.6050, recon=0.0017, vq=0.4226, div=0]

  [VQ Debug] e_loss=0.0174, q_loss=0.0174, usage=0.0336, total=0.0935

 41%|████      | 205/500 [05:15<07:35,  1.54s/it, loss=0.6067, recon=0.0017, vq=0.4242, div=0]

  [VQ Debug] e_loss=0.0388, q_loss=0.0388, usage=0.0083, total=0.0748

 42%|████▏     | 208/500 [05:19<07:21,  1.51s/it, loss=0.6114, recon=0.0017, vq=0.4289, div=0]

  [VQ Debug] e_loss=0.0625, q_loss=0.0625, usage=0.0848, total=0.2633
  [VQ Debug] e_loss=0.0208, q_loss=0.0208, usage=0.0385, total=0.1081

 43%|████▎     | 213/500 [05:27<07:20,  1.53s/it, loss=0.6167, recon=0.0017, vq=0.4346, div=0]

  [VQ Debug] e_loss=0.0181, q_loss=0.0181, usage=0.0394, total=0.1059

 45%|████▍     | 223/500 [05:42<07:04,  1.53s/it, loss=0.6053, recon=0.0017, vq=0.4237, div=0]

  [VQ Debug] e_loss=0.0175, q_loss=0.0175, usage=0.0338, total=0.0938

 45%|████▍     | 224/500 [05:45<06:59,  1.52s/it, loss=0.6088, recon=0.0017, vq=0.4269, div=0]

Epoch 225:
  Loss: 0.608752
  Recon: 0.001653
  VQ: 0.426917
  Unique semantic IDs: 7315/9828 (74.4%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 30.5
  Level 3: 127/128 (99.2%) | Perplexity: 101.1

 46%|████▌     | 229/500 [05:52<07:14,  1.60s/it, loss=0.6159, recon=0.0017, vq=0.4346, div=0]

  [VQ Debug] e_loss=0.0515, q_loss=0.0515, usage=0.0853, total=0.2479
  [VQ Debug] e_loss=0.0562, q_loss=0.0562, usage=0.0851, total=0.2545

 47%|████▋     | 234/500 [06:00<06:55,  1.56s/it, loss=0.6209, recon=0.0017, vq=0.4396, div=0]

  [VQ Debug] e_loss=0.0196, q_loss=0.0196, usage=0.0349, total=0.0992
  [VQ Debug] e_loss=0.0580, q_loss=0.0580, usage=0.0844, total=0.2559

 48%|████▊     | 238/500 [06:05<06:21,  1.46s/it, loss=0.6119, recon=0.0017, vq=0.4309, div=0]

  [VQ Debug] e_loss=0.0417, q_loss=0.0417, usage=0.0071, total=0.0768
  [VQ Debug] e_loss=0.0587, q_loss=0.0587, usage=0.0850, total=0.2581

 48%|████▊     | 240/500 [06:08<06:19,  1.46s/it, loss=0.6135, recon=0.0017, vq=0.4325, div=0]

  [VQ Debug] e_loss=0.0572, q_loss=0.0572, usage=0.0845, total=0.2548

 48%|████▊     | 241/500 [06:10<06:14,  1.45s/it, loss=0.6097, recon=0.0017, vq=0.4286, div=0]

  [VQ Debug] e_loss=0.0594, q_loss=0.0594, usage=0.0863, total=0.2618

 50%|████▉     | 248/500 [06:20<06:02,  1.44s/it, loss=0.6139, recon=0.0016, vq=0.4334, div=0]

  [VQ Debug] e_loss=0.0573, q_loss=0.0573, usage=0.0851, total=0.2562

 50%|████▉     | 249/500 [06:23<06:04,  1.45s/it, loss=0.6155, recon=0.0016, vq=0.4348, div=0]

Epoch 250:
  Loss: 0.615506
  Recon: 0.001648
  VQ: 0.434782
  Unique semantic IDs: 7285/9828 (74.1%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 30.7
  Level 3: 128/128 (100.0%) | Perplexity: 98.6

 51%|█████     | 255/500 [06:30<06:01,  1.47s/it, loss=0.6173, recon=0.0017, vq=0.4367, div=0]

  [VQ Debug] e_loss=0.0317, q_loss=0.0317, usage=0.0069, total=0.0615
  [VQ Debug] e_loss=0.0398, q_loss=0.0398, usage=0.0071, total=0.0739

 52%|█████▏    | 260/500 [06:37<05:46,  1.44s/it, loss=0.6320, recon=0.0017, vq=0.4512, div=0]

  [VQ Debug] e_loss=0.0215, q_loss=0.0215, usage=0.0373, total=0.1069

 52%|█████▏    | 261/500 [06:39<05:44,  1.44s/it, loss=0.6230, recon=0.0016, vq=0.4429, div=0]

  [VQ Debug] e_loss=0.0380, q_loss=0.0380, usage=0.0074, total=0.0719

 52%|█████▏    | 262/500 [06:40<05:49,  1.47s/it, loss=0.6137, recon=0.0017, vq=0.4332, div=0]

  [VQ Debug] e_loss=0.0205, q_loss=0.0205, usage=0.0324, total=0.0954

 53%|█████▎    | 263/500 [06:42<05:51,  1.48s/it, loss=0.6177, recon=0.0016, vq=0.4374, div=0]

  [VQ Debug] e_loss=0.0393, q_loss=0.0393, usage=0.0062, total=0.0714
  [VQ Debug] e_loss=0.0366, q_loss=0.0366, usage=0.0061, total=0.0672

 53%|█████▎    | 264/500 [06:43<05:46,  1.47s/it, loss=0.6117, recon=0.0016, vq=0.4314, div=0]

  [VQ Debug] e_loss=0.0652, q_loss=0.0652, usage=0.0856, total=0.2690

 53%|█████▎    | 265/500 [06:45<05:42,  1.46s/it, loss=0.6153, recon=0.0016, vq=0.4350, div=0]

  [VQ Debug] e_loss=0.0204, q_loss=0.0204, usage=0.0334, total=0.0974

 53%|█████▎    | 267/500 [06:48<05:34,  1.43s/it, loss=0.6137, recon=0.0016, vq=0.4336, div=0]

  [VQ Debug] e_loss=0.0403, q_loss=0.0403, usage=0.0067, total=0.0739
  [VQ Debug] e_loss=0.0694, q_loss=0.0694, usage=0.0858, total=0.2758

 54%|█████▍    | 270/500 [06:52<05:39,  1.48s/it, loss=0.6133, recon=0.0016, vq=0.4336, div=0]

  [VQ Debug] e_loss=0.0409, q_loss=0.0409, usage=0.0046, total=0.0706
  [VQ Debug] e_loss=0.0647, q_loss=0.0647, usage=0.0851, total=0.2672

 54%|█████▍    | 271/500 [06:54<05:37,  1.47s/it, loss=0.6096, recon=0.0016, vq=0.4298, div=0]

  [VQ Debug] e_loss=0.0392, q_loss=0.0392, usage=0.0079, total=0.0747

 55%|█████▍    | 274/500 [06:59<05:26,  1.44s/it, loss=0.6351, recon=0.0017, vq=0.4550, div=0]

Epoch 275:
  Loss: 0.635113
  Recon: 0.001653
  VQ: 0.455040
  Unique semantic IDs: 7269/9828 (74.0%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 30.9
  Level 3: 128/128 (100.0%) | Perplexity: 98.1

 56%|█████▌    | 279/500 [07:05<05:24,  1.47s/it, loss=0.6354, recon=0.0017, vq=0.4555, div=0]

  [VQ Debug] e_loss=0.0615, q_loss=0.0615, usage=0.0848, total=0.2619
  [VQ Debug] e_loss=0.0243, q_loss=0.0243, usage=0.0373, total=0.1109

 56%|█████▋    | 282/500 [07:10<05:17,  1.46s/it, loss=0.6282, recon=0.0016, vq=0.4486, div=0]

  [VQ Debug] e_loss=0.0487, q_loss=0.0487, usage=0.0063, total=0.0856
  [VQ Debug] e_loss=0.0598, q_loss=0.0598, usage=0.0850, total=0.2596

 57%|█████▋    | 284/500 [07:13<05:12,  1.45s/it, loss=0.6258, recon=0.0017, vq=0.4460, div=0]

  [VQ Debug] e_loss=0.0593, q_loss=0.0593, usage=0.0841, total=0.2571

 57%|█████▋    | 285/500 [07:14<05:12,  1.45s/it, loss=0.6310, recon=0.0016, vq=0.4512, div=0]

  [VQ Debug] e_loss=0.0218, q_loss=0.0218, usage=0.0366, total=0.1060

 58%|█████▊    | 288/500 [07:18<05:04,  1.44s/it, loss=0.6326, recon=0.0016, vq=0.4529, div=0]

  [VQ Debug] e_loss=0.0405, q_loss=0.0405, usage=0.0087, total=0.0783

 58%|█████▊    | 291/500 [07:23<05:16,  1.52s/it, loss=0.6208, recon=0.0016, vq=0.4414, div=0]

  [VQ Debug] e_loss=0.0238, q_loss=0.0238, usage=0.0328, total=0.1012

 60%|█████▉    | 299/500 [07:35<04:56,  1.48s/it, loss=0.6215, recon=0.0016, vq=0.4423, div=0]

  [VQ Debug] e_loss=0.0215, q_loss=0.0215, usage=0.0331, total=0.0983

 60%|█████▉    | 299/500 [07:36<04:56,  1.48s/it, loss=0.6373, recon=0.0016, vq=0.4578, div=0]

Epoch 300:
  Loss: 0.637325
  Recon: 0.001648
  VQ: 0.457825

 60%|██████    | 300/500 [07:37<05:46,  1.73s/it, loss=0.6373, recon=0.0016, vq=0.4578, div=0]

  Unique semantic IDs: 7233/9828 (73.6%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 30.6
  Level 3: 128/128 (100.0%) | Perplexity: 100.3

 60%|██████    | 302/500 [07:42<06:44,  2.04s/it, loss=0.6268, recon=0.0016, vq=0.4478, div=0]

  [VQ Debug] e_loss=0.0246, q_loss=0.0246, usage=0.0350, total=0.1068

 62%|██████▏   | 309/500 [07:54<05:32,  1.74s/it, loss=0.6335, recon=0.0017, vq=0.4541, div=0]

  [VQ Debug] e_loss=0.0600, q_loss=0.0600, usage=0.0853, total=0.2607

 62%|██████▏   | 312/500 [08:00<05:32,  1.77s/it, loss=0.6235, recon=0.0016, vq=0.4448, div=0]

  [VQ Debug] e_loss=0.0383, q_loss=0.0383, usage=0.0080, total=0.0735

 63%|██████▎   | 313/500 [08:01<05:34,  1.79s/it, loss=0.6237, recon=0.0016, vq=0.4446, div=0]

  [VQ Debug] e_loss=0.0449, q_loss=0.0449, usage=0.0079, total=0.0831

 63%|██████▎   | 314/500 [08:04<05:56,  1.92s/it, loss=0.6315, recon=0.0016, vq=0.4528, div=0]

  [VQ Debug] e_loss=0.0237, q_loss=0.0237, usage=0.0390, total=0.1137

 64%|██████▍   | 320/500 [08:14<05:02,  1.68s/it, loss=0.6403, recon=0.0016, vq=0.4616, div=0]

  [VQ Debug] e_loss=0.0652, q_loss=0.0652, usage=0.0854, total=0.2686

 65%|██████▍   | 324/500 [08:22<04:46,  1.63s/it, loss=0.6408, recon=0.0016, vq=0.4621, div=0]

Epoch 325:
  Loss: 0.640822
  Recon: 0.001640
  VQ: 0.462084
  Unique semantic IDs: 7082/9828 (72.1%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 30.9
  Level 3: 127/128 (99.2%) | Perplexity: 95.6

 65%|██████▌   | 325/500 [08:22<04:58,  1.71s/it, loss=0.6408, recon=0.0016, vq=0.4621, div=0]

  [VQ Debug] e_loss=0.0370, q_loss=0.0370, usage=0.0073, total=0.0700

 65%|██████▌   | 327/500 [08:25<04:52,  1.69s/it, loss=0.6191, recon=0.0016, vq=0.4407, div=0]

  [VQ Debug] e_loss=0.0709, q_loss=0.0709, usage=0.0856, total=0.2774
  [VQ Debug] e_loss=0.0248, q_loss=0.0248, usage=0.0308, total=0.0988

 66%|██████▌   | 328/500 [08:27<04:47,  1.67s/it, loss=0.6240, recon=0.0016, vq=0.4456, div=0]

  [VQ Debug] e_loss=0.0248, q_loss=0.0248, usage=0.0340, total=0.1052

 67%|██████▋   | 334/500 [08:37<04:34,  1.65s/it, loss=0.6234, recon=0.0016, vq=0.4450, div=0]

  [VQ Debug] e_loss=0.0685, q_loss=0.0685, usage=0.0865, total=0.2757

 67%|██████▋   | 337/500 [08:42<04:26,  1.63s/it, loss=0.6235, recon=0.0016, vq=0.4453, div=0]

  [VQ Debug] e_loss=0.0607, q_loss=0.0607, usage=0.0844, total=0.2598

 68%|██████▊   | 341/500 [08:49<04:13,  1.60s/it, loss=0.6301, recon=0.0016, vq=0.4518, div=0]

  [VQ Debug] e_loss=0.0434, q_loss=0.0434, usage=0.0075, total=0.0800

 69%|██████▊   | 343/500 [08:52<04:24,  1.69s/it, loss=0.6342, recon=0.0016, vq=0.4560, div=0]

  [VQ Debug] e_loss=0.0229, q_loss=0.0229, usage=0.0361, total=0.1066
  [VQ Debug] e_loss=0.0199, q_loss=0.0199, usage=0.0366, total=0.1031

 70%|██████▉   | 349/500 [09:03<04:01,  1.60s/it, loss=0.6374, recon=0.0016, vq=0.4593, div=0]

Epoch 350:
  Loss: 0.637427
  Recon: 0.001640
  VQ: 0.459349
  Unique semantic IDs: 7192/9828 (73.2%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 31.1
  Level 3: 128/128 (100.0%) | Perplexity: 101.5

 71%|███████   | 353/500 [09:08<03:58,  1.62s/it, loss=0.6368, recon=0.0016, vq=0.4587, div=0]

  [VQ Debug] e_loss=0.0221, q_loss=0.0221, usage=0.0381, total=0.1093
  [VQ Debug] e_loss=0.0212, q_loss=0.0212, usage=0.0380, total=0.1079

 72%|███████▏  | 361/500 [09:21<03:39,  1.58s/it, loss=0.6390, recon=0.0016, vq=0.4611, div=0]

  [VQ Debug] e_loss=0.0473, q_loss=0.0473, usage=0.0068, total=0.0845
  [VQ Debug] e_loss=0.0698, q_loss=0.0698, usage=0.0853, total=0.2752

 73%|███████▎  | 363/500 [09:24<03:40,  1.61s/it, loss=0.6409, recon=0.0016, vq=0.4634, div=0]

  [VQ Debug] e_loss=0.0232, q_loss=0.0232, usage=0.0404, total=0.1156

 73%|███████▎  | 365/500 [09:28<03:39,  1.62s/it, loss=0.6522, recon=0.0016, vq=0.4741, div=0]

  [VQ Debug] e_loss=0.0781, q_loss=0.0781, usage=0.0855, total=0.2880

 74%|███████▍  | 370/500 [09:36<03:27,  1.59s/it, loss=0.6397, recon=0.0016, vq=0.4621, div=0]

  [VQ Debug] e_loss=0.0836, q_loss=0.0836, usage=0.0861, total=0.2977

 74%|███████▍  | 371/500 [09:37<03:27,  1.61s/it, loss=0.6482, recon=0.0016, vq=0.4703, div=0]

  [VQ Debug] e_loss=0.0211, q_loss=0.0211, usage=0.0408, total=0.1132

 75%|███████▍  | 374/500 [09:44<03:25,  1.63s/it, loss=0.6429, recon=0.0016, vq=0.4651, div=0]

Epoch 375:
  Loss: 0.642918
  Recon: 0.001642
  VQ: 0.465142
  Unique semantic IDs: 7082/9828 (72.1%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 30.6
  Level 3: 128/128 (100.0%) | Perplexity: 97.1

 75%|███████▌  | 376/500 [09:46<03:29,  1.69s/it, loss=0.6260, recon=0.0016, vq=0.4500, div=0]

  [VQ Debug] e_loss=0.0430, q_loss=0.0430, usage=0.0086, total=0.0818

 76%|███████▌  | 380/500 [09:53<03:24,  1.70s/it, loss=0.6325, recon=0.0016, vq=0.4555, div=0]

  [VQ Debug] e_loss=0.0222, q_loss=0.0222, usage=0.0373, total=0.1079

 76%|███████▌  | 381/500 [09:54<03:26,  1.74s/it, loss=0.6349, recon=0.0016, vq=0.4575, div=0]

  [VQ Debug] e_loss=0.0411, q_loss=0.0411, usage=0.0065, total=0.0747
  [VQ Debug] e_loss=0.0630, q_loss=0.0630, usage=0.0861, total=0.2667

 77%|███████▋  | 384/500 [09:59<03:13,  1.67s/it, loss=0.6414, recon=0.0016, vq=0.4641, div=0]

  [VQ Debug] e_loss=0.0403, q_loss=0.0403, usage=0.0075, total=0.0755

 77%|███████▋  | 385/500 [10:01<03:09,  1.64s/it, loss=0.6453, recon=0.0016, vq=0.4677, div=0]

  [VQ Debug] e_loss=0.0254, q_loss=0.0254, usage=0.0370, total=0.1121

 77%|███████▋  | 386/500 [10:02<03:06,  1.64s/it, loss=0.6413, recon=0.0016, vq=0.4640, div=0]

  [VQ Debug] e_loss=0.0272, q_loss=0.0272, usage=0.0361, total=0.1131

 78%|███████▊  | 389/500 [10:07<02:57,  1.60s/it, loss=0.6444, recon=0.0016, vq=0.4670, div=0]

  [VQ Debug] e_loss=0.0657, q_loss=0.0657, usage=0.0848, total=0.2682

 79%|███████▊  | 393/500 [10:14<02:51,  1.61s/it, loss=0.6462, recon=0.0016, vq=0.4692, div=0]

  [VQ Debug] e_loss=0.0430, q_loss=0.0430, usage=0.0083, total=0.0812

 79%|███████▉  | 395/500 [10:17<02:49,  1.62s/it, loss=0.6486, recon=0.0016, vq=0.4714, div=0]

  [VQ Debug] e_loss=0.0225, q_loss=0.0225, usage=0.0407, total=0.1151
  [VQ Debug] e_loss=0.0426, q_loss=0.0426, usage=0.0067, total=0.0774

 80%|███████▉  | 399/500 [10:25<02:41,  1.60s/it, loss=0.6419, recon=0.0016, vq=0.4649, div=0]

Epoch 400:
  Loss: 0.641896
  Recon: 0.001629
  VQ: 0.464907
  Unique semantic IDs: 7192/9828 (73.2%)

 80%|████████  | 400/500 [10:25<02:50,  1.70s/it, loss=0.6419, recon=0.0016, vq=0.4649, div=0]

  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 30.8
  Level 3: 128/128 (100.0%) | Perplexity: 101.3

 81%|████████  | 403/500 [10:30<02:38,  1.64s/it, loss=0.6377, recon=0.0016, vq=0.4608, div=0]

  [VQ Debug] e_loss=0.0735, q_loss=0.0735, usage=0.0855, total=0.2813

 81%|████████  | 404/500 [10:32<02:37,  1.64s/it, loss=0.6397, recon=0.0016, vq=0.4629, div=0]

  [VQ Debug] e_loss=0.0655, q_loss=0.0655, usage=0.0853, total=0.2689

 81%|████████▏ | 407/500 [10:37<02:30,  1.62s/it, loss=0.6402, recon=0.0016, vq=0.4632, div=0]

  [VQ Debug] e_loss=0.0400, q_loss=0.0400, usage=0.0084, total=0.0767

 83%|████████▎ | 415/500 [10:49<02:15,  1.59s/it, loss=0.6527, recon=0.0016, vq=0.4755, div=0]

  [VQ Debug] e_loss=0.0705, q_loss=0.0705, usage=0.0854, total=0.2765

 83%|████████▎ | 416/500 [10:51<02:19,  1.66s/it, loss=0.6500, recon=0.0016, vq=0.4733, div=0]

  [VQ Debug] e_loss=0.0458, q_loss=0.0458, usage=0.0077, total=0.0840

 83%|████████▎ | 417/500 [10:53<02:21,  1.71s/it, loss=0.6485, recon=0.0016, vq=0.4718, div=0]

  [VQ Debug] e_loss=0.0609, q_loss=0.0609, usage=0.0854, total=0.2622

 84%|████████▎ | 418/500 [10:55<02:17,  1.67s/it, loss=0.6478, recon=0.0016, vq=0.4708, div=0]

  [VQ Debug] e_loss=0.0229, q_loss=0.0229, usage=0.0372, total=0.1088
  [VQ Debug] e_loss=0.0657, q_loss=0.0657, usage=0.0854, total=0.2693
  [VQ Debug] e_loss=0.0516, q_loss=0.0516, usage=0.0080, total=0.0935

 84%|████████▍ | 419/500 [10:56<02:16,  1.68s/it, loss=0.6417, recon=0.0016, vq=0.4650, div=0]

  [VQ Debug] e_loss=0.0712, q_loss=0.0712, usage=0.0863, total=0.2793

 84%|████████▍ | 420/500 [10:58<02:14,  1.68s/it, loss=0.6499, recon=0.0016, vq=0.4734, div=0]

  [VQ Debug] e_loss=0.0250, q_loss=0.0250, usage=0.0379, total=0.1134

 84%|████████▍ | 421/500 [11:00<02:11,  1.67s/it, loss=0.6463, recon=0.0016, vq=0.4699, div=0]

  [VQ Debug] e_loss=0.0716, q_loss=0.0716, usage=0.0849, total=0.2771
  [VQ Debug] e_loss=0.0230, q_loss=0.0230, usage=0.0364, total=0.1074

 85%|████████▍ | 424/500 [11:06<02:03,  1.62s/it, loss=0.6459, recon=0.0016, vq=0.4693, div=0]

  [VQ Debug] e_loss=0.0236, q_loss=0.0236, usage=0.0384, total=0.1122

Epoch 425:
  Loss: 0.645898
  Recon: 0.001633
  VQ: 0.469345

 85%|████████▌ | 425/500 [11:06<02:07,  1.70s/it, loss=0.6459, recon=0.0016, vq=0.4693, div=0]

  Unique semantic IDs: 7046/9828 (71.7%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 31.1
  Level 3: 128/128 (100.0%) | Perplexity: 97.8
  [VQ Debug] e_loss=0.0214, q_loss=0.0214, usage=0.0381, total=0.1083
  [VQ Debug] e_loss=0.0353, q_loss=0.0353, usage=0.0075, total=0.0679

 87%|████████▋ | 434/500 [11:21<01:44,  1.59s/it, loss=0.6511, recon=0.0016, vq=0.4744, div=0]

  [VQ Debug] e_loss=0.0681, q_loss=0.0681, usage=0.0852, total=0.2725

 87%|████████▋ | 437/500 [11:26<01:41,  1.61s/it, loss=0.6512, recon=0.0016, vq=0.4748, div=0]

  [VQ Debug] e_loss=0.0407, q_loss=0.0407, usage=0.0091, total=0.0792

 88%|████████▊ | 441/500 [11:32<01:33,  1.59s/it, loss=0.6439, recon=0.0016, vq=0.4676, div=0]

  [VQ Debug] e_loss=0.0456, q_loss=0.0456, usage=0.0083, total=0.0849
  [VQ Debug] e_loss=0.0676, q_loss=0.0676, usage=0.0859, total=0.2732

 88%|████████▊ | 442/500 [11:34<01:33,  1.61s/it, loss=0.6396, recon=0.0016, vq=0.4635, div=0]

  [VQ Debug] e_loss=0.0214, q_loss=0.0214, usage=0.0382, total=0.1084

 89%|████████▉ | 447/500 [11:42<01:23,  1.58s/it, loss=0.6418, recon=0.0016, vq=0.4655, div=0]

  [VQ Debug] e_loss=0.0263, q_loss=0.0263, usage=0.0365, total=0.1124
  [VQ Debug] e_loss=0.0257, q_loss=0.0257, usage=0.0378, total=0.1143

 90%|████████▉ | 449/500 [11:47<01:21,  1.59s/it, loss=0.6497, recon=0.0016, vq=0.4733, div=0]

Epoch 450:
  Loss: 0.649696
  Recon: 0.001627
  VQ: 0.473310
  Unique semantic IDs: 6996/9828 (71.2%)
  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 30.4
  Level 3: 128/128 (100.0%) | Perplexity: 94.7

 90%|█████████ | 452/500 [11:50<01:22,  1.71s/it, loss=0.6459, recon=0.0016, vq=0.4698, div=0]

  [VQ Debug] e_loss=0.0711, q_loss=0.0711, usage=0.0855, total=0.2776
  [VQ Debug] e_loss=0.0267, q_loss=0.0267, usage=0.0366, total=0.1133

 91%|█████████ | 453/500 [11:52<01:21,  1.73s/it, loss=0.6582, recon=0.0016, vq=0.4815, div=0]

  [VQ Debug] e_loss=0.0643, q_loss=0.0643, usage=0.0857, total=0.2678

 93%|█████████▎| 465/500 [12:11<00:55,  1.57s/it, loss=0.6524, recon=0.0016, vq=0.4764, div=0]

  [VQ Debug] e_loss=0.0512, q_loss=0.0512, usage=0.0063, total=0.0894

 94%|█████████▎| 468/500 [12:16<00:51,  1.59s/it, loss=0.6604, recon=0.0016, vq=0.4845, div=0]

  [VQ Debug] e_loss=0.0726, q_loss=0.0726, usage=0.0852, total=0.2794
  [VQ Debug] e_loss=0.0721, q_loss=0.0721, usage=0.0855, total=0.2791

 94%|█████████▍| 470/500 [12:19<00:48,  1.62s/it, loss=0.6515, recon=0.0016, vq=0.4759, div=0]

  [VQ Debug] e_loss=0.0243, q_loss=0.0243, usage=0.0381, total=0.1126

 94%|█████████▍| 471/500 [12:21<00:47,  1.63s/it, loss=0.6497, recon=0.0016, vq=0.4740, div=0]

  [VQ Debug] e_loss=0.0670, q_loss=0.0670, usage=0.0857, total=0.2719

 95%|█████████▍| 473/500 [12:24<00:44,  1.64s/it, loss=0.6445, recon=0.0016, vq=0.4686, div=0]

  [VQ Debug] e_loss=0.0848, q_loss=0.0848, usage=0.0856, total=0.2984

 95%|█████████▍| 474/500 [12:28<00:42,  1.62s/it, loss=0.6538, recon=0.0016, vq=0.4779, div=0]

Epoch 475:
  Loss: 0.653829
  Recon: 0.001625
  VQ: 0.477894
  Unique semantic IDs: 7091/9828 (72.2%)

 95%|█████████▌| 475/500 [12:28<00:42,  1.71s/it, loss=0.6538, recon=0.0016, vq=0.4779, div=0]

  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 30.7
  Level 3: 127/128 (99.2%) | Perplexity: 98.0

 95%|█████████▌| 477/500 [12:31<00:38,  1.69s/it, loss=0.6357, recon=0.0016, vq=0.4600, div=0]

  [VQ Debug] e_loss=0.0540, q_loss=0.0540, usage=0.0066, total=0.0943

 96%|█████████▌| 478/500 [12:33<00:36,  1.68s/it, loss=0.6438, recon=0.0016, vq=0.4679, div=0]

  [VQ Debug] e_loss=0.0690, q_loss=0.0690, usage=0.0856, total=0.2748

 97%|█████████▋| 483/500 [12:42<00:29,  1.74s/it, loss=0.6421, recon=0.0016, vq=0.4667, div=0]

  [VQ Debug] e_loss=0.0396, q_loss=0.0396, usage=0.0078, total=0.0751

 97%|█████████▋| 487/500 [12:48<00:21,  1.66s/it, loss=0.6626, recon=0.0016, vq=0.4872, div=0]

  [VQ Debug] e_loss=0.0264, q_loss=0.0264, usage=0.0368, total=0.1130

 98%|█████████▊| 488/500 [12:50<00:19,  1.64s/it, loss=0.6487, recon=0.0016, vq=0.4731, div=0]

  [VQ Debug] e_loss=0.0306, q_loss=0.0306, usage=0.0389, total=0.1237

 98%|█████████▊| 490/500 [12:53<00:17,  1.72s/it, loss=0.6480, recon=0.0016, vq=0.4724, div=0]

  [VQ Debug] e_loss=0.0425, q_loss=0.0425, usage=0.0067, total=0.0771
  [VQ Debug] e_loss=0.0487, q_loss=0.0487, usage=0.0067, total=0.0865

 98%|█████████▊| 492/500 [12:57<00:13,  1.69s/it, loss=0.6605, recon=0.0016, vq=0.4849, div=0]

  [VQ Debug] e_loss=0.0851, q_loss=0.0851, usage=0.0850, total=0.2976

 99%|█████████▉| 495/500 [13:02<00:08,  1.63s/it, loss=0.6412, recon=0.0016, vq=0.4662, div=0]

  [VQ Debug] e_loss=0.0605, q_loss=0.0605, usage=0.0848, total=0.2602
  [VQ Debug] e_loss=0.0219, q_loss=0.0219, usage=0.0356, total=0.1042

100%|█████████▉| 499/500 [13:10<00:01,  1.59s/it, loss=0.6624, recon=0.0016, vq=0.4870, div=0]

Epoch 500:
  Loss: 0.662355
  Recon: 0.001631
  VQ: 0.487045
  Unique semantic IDs: 6973/9828 (71.0%)

100%|██████████| 500/500 [13:10<00:00,  1.58s/it, loss=0.6624, recon=0.0016, vq=0.4870, div=0]

  Level 1: 13/16 (81.2%) | Perplexity: 12.6
  Level 2: 32/32 (100.0%) | Perplexity: 30.8
  Level 3: 128/128 (100.0%) | Perplexity: 97.8

Generating semantic IDs...
Generated 9828 semantic IDs
  Level 1: 13 unique codes
  Level 2: 32 unique codes
  Level 3: 128 unique codes

============================================================
SEMANTIC ID EVALUATION REPORT
============================================================

1. RECONSTRUCTION QUALITY
------------------------------------------------------------
Reconstruction Metrics (Original Input Space):
  MSE: 0.0016 (lower is better, target < 0.1)
  Cosine Similarity: 0.6615 (higher is better, target > 0.9)
  Correlation: 0.6564 (target > 0.85)

2. CLUSTERING QUALITY
------------------------------------------------------------
Clustering Metrics (Top-Level Codes):
  Silhouette Score: -0.005 (range: -1 to 1, target > 0.3)
  Calinski-Harabasz: 2.6 (higher is better)

Clustering Metrics (Second-Level Codes):
  Silhouette Score: -0.053

3. SEMANTIC COHERENCE
------------------------------------------------------------
Debug: Star Wars ID: (9, 17, 1), Star Trek ID: (13, 4, 20), Matches: 0
✗ Star Wars                      vs Star Trek                     : 0/3 levels match (expected: high)

Passed: 0/1 tests

4. CODEBOOK UTILIZATION
------------------------------------------------------------

Level 1 (Codebook size: 16):
  Used codes: 13/16 (81.2%)
  Min usage: 452 items
  Max usage: 1095 items
  Mean usage: 756.0 items

Level 2 (Codebook size: 32):
  Used codes: 32/32 (100.0%)
  Min usage: 180 items
  Max usage: 497 items
  Mean usage: 307.1 items

Level 3 (Codebook size: 128):
  Used codes: 128/128 (100.0%)
  Min usage: 2 items
  Max usage: 161 items
  Mean usage: 76.8 items

============================================================
OVERALL ASSESSMENT
============================================================
✗ Reconstruction: POOR - Consider larger codebooks
✗ Clustering: POOR - Check encoder quality
✗ Semantic Coherence: POOR - Review text encoding strategy

❌ Semantic IDs need significant improvement before production.

In [15]:
# Enhanced diagnostics - check loss components
import torch

print("="*70)
print("TRAINING DIAGNOSTICS")
print("="*70)

# 1. Check encoder output variance
with torch.no_grad():
    encoder_output = pipeline.rqvae.encoder(data_tensor[:100])
    print(f"\n1. Encoder Output:")
    print(f"   Std: {encoder_output.std().item():.4f}")
    print(f"   Mean: {encoder_output.mean().item():.4f}")
    print(f"   Min: {encoder_output.min().item():.4f}")
    print(f"   Max: {encoder_output.max().item():.4f}")

# 2. Check codebook usage and get actual loss values
print(f"\n2. Codebook Usage:")
for level_idx, vq in enumerate(pipeline.rqvae.quantizers):
    with torch.no_grad():
        if level_idx == 0:
            z = pipeline.rqvae.encoder(data_tensor)
        else:
            z = pipeline.rqvae.encoder(data_tensor)
            for prev_vq in pipeline.rqvae.quantizers[:level_idx]:
                z, _, _ = prev_vq(z)
        
        # Get loss components
        vq.train()
        quantized, vq_loss, indices = vq(z)
        
        unique_codes = torch.unique(indices).numel()
        
    print(f"\n   Level {level_idx+1} (size={codebook_sizes[level_idx]}):")
    print(f"   - Unique codes: {unique_codes}/{codebook_sizes[level_idx]} ({100*unique_codes/codebook_sizes[level_idx]:.1f}%)")
    print(f"   - VQ loss: {vq_loss.item():.4f}")
    print(f"   - Usage weight: {vq.usage_loss_weight}")

# 3. Check full forward pass
print(f"\n3. Full Forward Pass:")
with torch.no_grad():
    reconstructed, total_loss, codes = pipeline.rqvae(data_tensor[:100])
    recon_error = ((data_tensor[:100] - reconstructed) ** 2).mean()
    
    print(f"   - Reconstruction error: {recon_error.item():.6f}")
    print(f"   - Total VQ loss: {total_loss.item():.4f}")

print("\n" + "="*70)

======================================================================
TRAINING DIAGNOSTICS
======================================================================

1. Encoder Output:
   Std: 1.0857
   Mean: -0.0039
   Min: -3.6844
   Max: 4.0595

2. Codebook Usage:

   Level 1 (size=16):
   - Unique codes: 13/16 (81.2%)
   - VQ loss: 0.2755
   - Usage weight: 2.0

   Level 2 (size=32):
   - Unique codes: 9/32 (28.1%)
   - VQ loss: 1.5567
   - Usage weight: 2.0

   Level 3 (size=128):
   - Unique codes: 6/128 (4.7%)
   - VQ loss: 0.7031
   - Usage weight: 2.0

3. Full Forward Pass:
   - Reconstruction error: 0.001593
   - Total VQ loss: 0.4749

======================================================================

In [16]:
df_enriched.head()

,Release_Date,title,description,Popularity,Vote_Count,Vote_Average,Original_Language,genres,Poster_Url,semantic_id,leaf_id,final_id
4725,2013-02-01,Journey to the West: Conquering the Demons,In a world plagued by demons who cause great h...,21.870,248,7.0,zh,"Action, Fantasy, Adventure, Comedy",https://image.tmdb.org/t/p/original/XcFMQQfx1g...,"(1, 0, 111)",0,"(1, 0, 111, 0)"
9664,2019-04-05,The Head Hunter,"On the outskirts of a kingdom, a quiet but fie...",13.492,214,5.4,en,"Horror, Fantasy",https://image.tmdb.org/t/p/original/ol0DSLOIN8...,"(1, 0, 122)",0,"(1, 0, 122, 0)"
9520,2008-12-30,Jack Hunter and the Quest for Akhenaten's Tomb,Adventurer Jack Hunter sets off in pursuit of ...,13.631,22,6.4,en,Adventure,https://image.tmdb.org/t/p/original/AkjACojVQ8...,"(1, 0, 2)",0,"(1, 0, 2, 0)"
5494,1961-05-01,The Curse of the Werewolf,A child conceived after a demented beggar rape...,19.640,116,6.5,en,Horror,https://image.tmdb.org/t/p/original/nwtxrG9jd5...,"(1, 0, 21)",0,"(1, 0, 21, 0)"
815,2021-05-05,Those Who Wish Me Dead,A young boy finds himself pursued by two assas...,75.887,1089,6.8,en,Thriller,https://image.tmdb.org/t/p/original/xCEg6KowNI...,"(1, 0, 34)",0,"(1, 0, 34, 0)"

In [17]:

importlib.reload(recsys.semantic_ids.evaluations)
from matplotlib.pyplot import title
from recsys.semantic_ids.evaluations import test_semantic_coherence

# test_semantic_coherence(df_enriched)
def get_row(title, df):
    return df[df['title'] == title]['semantic_id'].values[0]
get_row("Star Wars", df_enriched)

(9, 17, 1)

In [18]:
df_enriched['title'].str.startswith('Star Wars')

4725    False
9664    False
9520    False
5494    False
815     False
        ...
3499    False
8023    False
245     False
6075    False
702     False
Name: title, Length: 9828, dtype: bool

In [19]:
df_enriched = df_enriched[df_enriched.isna() == False]

df_enriched[df_enriched['title'].isna()]

Empty DataFrame
Columns: [Release_Date, title, description, Popularity, Vote_Count, Vote_Average, Original_Language, genres, Poster_Url, semantic_id, leaf_id, final_id]
Index: []

In [20]:
df_enriched[df_enriched['title'].str.startswith('Star Wars')]

,Release_Date,title,description,Popularity,Vote_Count,Vote_Average,Original_Language,genres,Poster_Url,semantic_id,leaf_id,final_id
2631,2008-08-05,Star Wars: The Clone Wars,"Set between Episode II and III, The Clone Wars...",33.496,1532,6.1,en,"Animation, Action, Science Fiction, Adventure",https://image.tmdb.org/t/p/original/ywRtBu88SL...,"(2, 4, 89)",0,"(2, 4, 89, 0)"
1725,1999-05-19,Star Wars: Episode I - The Phantom Menace,"Anakin Skywalker, a young slave strong with th...",45.562,11924,6.5,en,"Adventure, Action, Science Fiction",https://image.tmdb.org/t/p/original/6wkfovpn7E...,"(9, 1, 94)",3,"(9, 1, 94, 3)"
1615,2002-05-15,Star Wars: Episode II - Attack of the Clones,Following an assassination attempt on Senator ...,47.917,10781,6.5,en,"Adventure, Action, Science Fiction",https://image.tmdb.org/t/p/original/oZNPzxqM2s...,"(9, 1, 94)",4,"(9, 1, 94, 4)"
1926,2005-05-17,Star Wars: Episode III - Revenge of the Sith,The evil Darth Sidious enacts his final plan f...,41.997,11189,7.4,en,"Science Fiction, Adventure, Action",https://image.tmdb.org/t/p/original/xfSAoBEm9M...,"(9, 1, 94)",5,"(9, 1, 94, 5)"
785,2015-12-15,Star Wars: The Force Awakens,Thirty years after defeating the Galactic Empi...,77.811,16772,7.3,en,"Action, Adventure, Science Fiction, Fantasy",https://image.tmdb.org/t/p/original/wqnLdwVXoB...,"(9, 1, 94)",6,"(9, 1, 94, 6)"
847,2017-12-13,Star Wars: The Last Jedi,Rey develops her newly discovered abilities wi...,73.522,12808,6.9,en,"Science Fiction, Action, Adventure",https://image.tmdb.org/t/p/original/kOVEVeg59E...,"(9, 1, 94)",7,"(9, 1, 94, 7)"
748,2019-12-18,Star Wars: The Rise of Skywalker,The surviving Resistance faces the First Order...,79.730,7588,6.4,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/db32LaOibw...,"(9, 1, 94)",8,"(9, 1, 94, 8)"
625,1977-05-25,Star Wars,Princess Leia is captured and held hostage by ...,90.969,16952,8.2,en,"Adventure, Action, Science Fiction",https://image.tmdb.org/t/p/original/6FfCtAuVAW...,"(9, 17, 1)",0,"(9, 17, 1, 0)"

In [21]:

def investigate_cluster(df):# Check what's in the largest cluster
    largest_cluster_id = df['semantic_id'].value_counts().head(1).index[0]
    largest_cluster = df[df['semantic_id'] == largest_cluster_id]

    print(f"Items in cluster {largest_cluster_id}: {len(largest_cluster)}")
    print("\nSample titles:")
    print(largest_cluster[['title', 'genres']].head(20))

    print("\nGenre distribution:")
    
    print(largest_cluster['genres'].value_counts().head(10))

investigate_cluster(df_enriched)

Items in cluster (10, 30, 20): 39

Sample titles:
                                        title  \
2033                        Aloha Scooby-Doo!
8624                      Big Top Scooby-Doo!
3664                   Chill Out, Scooby-Doo!
954              Happy Halloween, Scooby-Doo!
7655      LEGO Scooby-Doo! Blowout Beach Bash
891                                    Scoob!
443                                Scooby-Doo
1674         Scooby-Doo 2: Monsters Unleashed
7232          Scooby-Doo and the Ghoul School
3306              Scooby-Doo on Zombie Island
3901              Scooby-Doo! Abracadabra-Doo
6209  Scooby-Doo! Adventures: The Mystery Map
2665                   Scooby-Doo! Camp Scare
2213    Scooby-Doo! Curse of the Lake Monster
5921                Scooby-Doo! Frankencreepy
4991     Scooby-Doo! Legend of the Phantosaur
5988      Scooby-Doo! Mask of the Blue Falcon
7690       Scooby-Doo! Meets the Boo Brothers
6529         Scooby-Doo! Moon Monster Madness
6107         Scooby-Doo! Music of the Vampire

                                                 genres
2033      Mystery, Family, Animation, Adventure, Comedy
8624                 Family, Animation, Comedy, Mystery
3664      Family, Comedy, Animation, Adventure, Mystery
954                  Family, Animation, Mystery, Comedy
7655                 Animation, Comedy, Family, Mystery
891                Animation, Family, Comedy, Adventure
443                          Mystery, Adventure, Comedy
1674                Mystery, Fantasy, Adventure, Comedy
7232  Animation, Mystery, Family, TV Movie, Comedy, ...
3306  Animation, Comedy, Family, Mystery, Adventure,...
3901        Animation, Comedy, Family, Mystery, Fantasy
6209                 Family, Comedy, Mystery, Animation
2665                 Animation, Comedy, Family, Mystery
2213                Mystery, Fantasy, Comedy, Adventure
5921                 Mystery, Animation, Family, Comedy
4991                 Family, Mystery, Animation, Comedy
5988      Animation, Comedy, Fantasy, Adventure, Family
7690     Animation, Adventure, Comedy, Family, TV Movie
6529  Adventure, Animation, Family, Comedy, Mystery,...
6107  Family, Animation, Mystery, Adventure, Comedy,...

Genre distribution:
genres
Animation, Comedy, Family, Mystery               4
Family, Animation, Comedy, Mystery               2
Animation, Adventure, Comedy                     1
Animation, Comedy, Family, Adventure             1
Animation, Family, Mystery, Comedy, Western      1
Family, Adventure, Animation, Comedy, Mystery    1
Mystery, Animation, Comedy, Fantasy              1
Family, Animation, Comedy                        1
Comedy, Family, Animation, Adventure, Mystery    1
Mystery, Family, Animation, Adventure, Comedy    1
Name: count, dtype: int64